di:
    instance:
        alias:
            assetwig-strategy: Assetwig\View\TwigStrategy
            assetwig-environment: Assetwig\Twig\Environment
            assetwig-resolver: Assetwig\View\TwigResolver
            assetwig-extension: Assetwig\Twig\Extension
            # for some reason can't use alias for TwigRenderer

            assetwig-assetic: Assetwig\Assetic\Assetic

            assetic-factory: Assetic\Factory\AssetFactory
            assetic-am: Assetic\AssetManager
            assetic-fm: Assetic\FilterManager
            assetic-lazy-am: Assetic\Factory\LazyAssetManager
            assetic-assetwriter: Assetwig\Assetic\AssetWriter
            assetic-extension: Assetic\Extension\Twig\AsseticExtension
        assetwig-strategy:
            parameters:
                renderer: Assetwig\View\TwigRenderer
        Assetwig\View\TwigRenderer:
            parameters:
                environment: assetwig-environment
                assetic: assetwig-assetic
        assetwig-environment:
            parameters:
                loader: assetwig-resolver
                options: {}
                extensionClasses:
                    Assetwig: assetwig-extension
                    Assetic: assetic-extension
        assetwig-assetic:
            parameters:
                environment: assetwig-environment
                lazyAssetManager: assetic-lazy-am
                assetWriter: assetic-assetwriter
                factory: assetic-factory
        assetic-extension:
            parameters:
                factory: assetic-factory
                functions: {}
        assetic-factory:
            parameters:
                am: assetic-am
                fm: assetic-fm
        assetic-lazy-am:
            parameters:
                factory: assetic-factory
                loaders: {}
        assetic-assetwriter:
            parameters:
                varValues: {}
view_manager:
    strategies:
        assetwig: Assetwig\View\TwigStrategy
