di:
    instance:
        alias:
            assetwig-strategy: Assetwig\View\TwigStrategy
            assetwig-environment: Assetwig\Twig\Environment
            assetwig-resolver: Assetwig\View\TwigResolver
            assetwig-extension: Assetwig\Twig\Extension
            # for some reason can't use alias for TwigRenderer

            assetwig-assetic: Assetwig\Assetic\Assetic

            assetic-am: Assetic\AssetManager
            assetic-fm: Assetic\FilterManager
            assetic-assetwriter: Assetwig\Assetic\AssetWriter
        assetwig-strategy:
            parameters:
                renderer: Assetwig\View\TwigRenderer
        Assetwig\View\TwigRenderer:
            parameters:
                environment: assetwig-environment
                assetic: assetwig-assetic
        assetwig-environment:
            parameters:
                loader: assetwig-resolver
                options: {}
                extensionClasses:
                    Assetwig: assetwig-extension
        assetwig-assetic:
            parameters:
                environment: assetwig-environment
                assetWriter: assetic-assetwriter
        assetic-assetwriter:
            parameters:
                varValues: {}
view_manager:
    strategies:
        assetwig: Assetwig\View\TwigStrategy
